#!bin/bash

git checkout main
git pull
git checkout server-config
git merge main

# sudo find /home/yordam/balor -name "*.pyc" -delete
# sudo find /home/yordam/balor -name "__pycache__" -delete

sudo /home/jetson/miniconda3/envs/gupur/bin/python gui.py
